src/qt/darksilkgui.cpp
src/qt/darksilkgui.h
src/qt/sendcoinsdialog.cpp

Fixed and tested locking and unlocking for staking and sending coins.
Also did some minor cleanup in sendcoinsdialog.cpp

Fixed issues with padlock icon

---

src/qt/darksilkgui.cpp

Changed padlock icon functionality to match menu functionality.

Updated Unlock/Lock Functionality

---

src/market.cpp

This code was forked from Sling to Crave. It is corrected in the Crave source. Thanks!

Update market.cpp Copyright notice

---

contrib/gitian-descriptors/gitian-win.yml
darksilk-qt.pro

Windows compilation fixes

---

darksilk-qt.pro
src/main.cpp
src/main.h
src/qt/clientmodel.cpp
src/qt/clientmodel.h
src/qt/darksilkgui.cpp
src/qt/darksilkgui.h
src/qt/debugconsole.cpp
src/qt/debugconsole.h
src/qt/forms/debugconsole.ui
src/qt/guiutil.cpp
src/qt/guiutil.h
src/qt/peertablemodel.cpp
src/qt/peertablemodel.h

Also added Berkeley db version.
need to track down ping time, sync height, and ban score for peer table.

added peers table to wallet UI.

---

src/main.cpp
src/main.h
src/stormnode-budget.cpp
src/wallet.cpp

Added cscript payee to cblock and fixed compile errors.

---

src/main.cpp
src/main.h

reverted AcceptToMemoryPool function.
I don't have access to the repo anymore.

Fixes transaction sending errors.

---

darksilk-qt.pro
src/amount.cpp
src/amount.h
src/init.cpp
src/main.cpp
src/main.h
src/makefile.bsd
src/makefile.linux-mingw
src/makefile.mingw
src/makefile.osx
src/makefile.unix
src/obj/crypto/placeholder.txt
src/obj/primitives/placeholder.txt
src/primitives/transaction.h
src/qt/transactiondesc.cpp
src/txmempool.cpp
src/txmempool.h
src/util.cpp
src/util.h
src/wallet.cpp
src/wallet.h

also fixes segfault in leveldb on shutdown.

Implements fee estimate file. Adds amount.cpp/h. Fixes ReadConfigFile.

---

src/chain.h
src/hash.h
src/main.h
src/version.h
src/wallet.cpp

and bumped version.  some fixes to the Argon2d implementation.

Changed minimum transaction fee to 0.00001 DRKSLK.

---

src/txmempool.cpp
src/txmempool.h
src/wallet.cpp
src/wallet.h

Fixes to tx error test ????

---

src/chainparams.cpp
src/hash.h

genesis needed to be updated due to change in Argon2d time cost parameter.

Updates Argon2d genesis blocks for main and testnet.

---

src/addrman.h
src/chain.cpp
src/chain.h
src/chainparams.cpp
src/chainparams.h
src/kernel.cpp
src/kernel.h
src/net.h
src/primitives/block.cpp
src/primitives/block.h
src/protocol.cpp
src/protocol.h
src/qt/flowlayout.h
src/scrypt.cpp
src/scrypt.h
src/stormnodeconfig.h

Rearrange includes part II.

---

README.md
darksilk-qt.pro
src/qt/darksilkunits.cpp
src/qt/darksilkunits.h
src/qt/transactionrecord.h
src/qt/transactiontablemodel.cpp
src/qt/transactiontablemodel.h

* Fixes transaction table amount display issue in the wallet UI caused when adding watch only.
* Adds linking to GMP & Snappy for Linux to the Qt project file.  
* Updates the readme to reflect the needed GMP & Snappy dev library installation.
* Formatting to the readme that removes the horizontal scrolls in the build steps.

Transaction amount column & Link to GMP, Snappy Libs

---

README.md
src/makefile.bsd
src/makefile.linux-mingw
src/makefile.mingw
src/makefile.osx
src/makefile.unix
src/miner.cpp
src/rpc/rpcmisc.cpp

reduces debug.log over printing and fixes compile warnings.

Corrects daemon builds issues after code move

---

src/alert.cpp
src/alert.h
src/chain.h
src/chainparams.h
src/checkpoints.cpp
src/checkpoints.h
src/main.cpp
src/main.h
src/miner.cpp
src/primitives/transaction.cpp
src/primitives/transaction.h
src/streams.h
src/txmempool.cpp
src/txmempool.h
src/undo.h

Adds preliminary objects needed for chainActive.

chainActive Part I of IV.

---

CONTRIBUTING.md
src/main.cpp
src/net.cpp
src/util.cpp
src/util.h

fixes your compile errors in net.cpp.  It runs but still untested.

Net changes

---

darksilk-qt.pro
src/limitedmap.h
src/main.cpp
src/main.h
src/net.cpp
src/net.h

* adds and utilizes limitedmap for CNode
* refactors MAX_INV_SZ to net.h
* updates to I2P within CNode
code cherry picked from Spencer's previous commits to master branch.

Updates to CNode and I2P

---

.travis.yml
README.md
darksilk-qt.pro
doc/developer-notes.md

After this pull, I needed to uninstall libsnappy-dev to get the Qt wallet and daemon to build on the same machine.
`$ sudo apt-get remove libsnappy-dev`
make sure you make clean after uninstalling libsnappy-dev

Doc & Build: Adds Developer Notes & Tests Travis

---

PULL_REQUEST_TEMPLATE.md

first draft for a pull request template:
- Does the readme or documentaion need an update?
- Does this add new C++ dependencies which need to be added?
- Does this change the chain or fork the network?

Repo: Adds pull request template

---

src/main.cpp
src/main.h
src/txmempool.cpp
src/txmempool.h

adds DisconnectTip used to implement chainActive.
PoW, PoS, send/receiving transactions all working after this pull request.
Code forked from Bitcoin v0.12.99

chainActive: DisconnectTip complete.

---

PULL_REQUEST_TEMPLATE.md

This removes the next question which is not very useful.
No needed.
- Does the readme or documentaion need an update? No.
- Does this add new C++ dependencies which need to be added? No.
- Does this change the chain or fork the network? No.

Repo: Removed pull request question.

---

src/main.h
src/wallet/wallet.h

Moves static const double MIN_FEE to wallet.h from main.h
Builds

Move static const double MIN_FEE to wallet.h from main.h

---

src/miner.cpp

Checks for peers and a full chain before running the internal PoW miner with setgenerate.
Yes.
- Does the readme or documentaion need an update? No.
- Does this add new C++ dependencies which need to be added? No.
- Does this change the chain or fork the network? No.

PoW: setgenerate does not run without peers or full chain.

---

src/wallet/wallet.cpp

Update to CreateCoinStake

---

darksilk-qt.pro
src/prevector.h
src/script/script.h

Adds prevector to the core and will be used by CScript.
Yes, works fine.
Needed to implement chainActive.
- Does the readme or documentaion need an update? No.
- Does this add new C++ dependencies which need to be added? No.
- Does this change the chain or fork the network? No.

chainActive: Adds prevector header file.

---

src/anon/stormnode/stormnode-budget.cpp
src/anon/stormnode/stormnode-budget.h
src/anon/stormnode/stormnode-sync.cpp
src/anon/stormnode/stormnode.cpp
src/anon/stormnode/stormnode.h
src/init.cpp
src/rpc/rpcstormnode-budget.cpp
src/util.cpp
src/util.h

Dash fixes for stormnodes.
No errors or warnings on build.
- Does the readme or documentaion need an update? no
- Does this add new C++ dependencies which need to be added? no
- Does this change the chain or fork the network? no

Dashupdates

---

src/rpc/rpcprotocol.h

Reorders includes for Windows
Builds in Linux but requires a Windows build test.
Working off of Cisahasa's information.

Reorder Includes for Windows

---

README.md
contrib/gitian-descriptors/README
contrib/gitian-descriptors/gitian-linux.yml
contrib/gitian-descriptors/gitian-osx.yml
contrib/gitian-descriptors/gitian-win.yml
doc/build-osx.txt

Changes GitHub urls in descriptors and ReadMe.
Yes

descriptors

---

src/i2p/i2psam.cpp

CloseSocket->closesocket

---

ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

It adds an issue template and updates our pull request template.  
Yes in other repos this has been tested: [pull test example](https://github.com/AmirAbrams/bitcoin/pull/3)
Pull request and issue templates are new to Github and the issue template is not yet implemented in this repo: [Github pull-request-templates] (https://github.com/blog/2111-issue-and-pull-request-templates)

[Doc] Adds issue template and updates pull request template.

---

darksilk-qt.pro
src/consensus/consensus.h
src/main.cpp
src/main.h
src/miner.cpp
src/net.cpp
src/primitives/transaction.cpp
src/primitives/transaction.h
src/qt/transactiondesc.cpp
src/qt/transactionrecord.cpp
src/rpc/rpcmining.cpp
src/txmempool.cpp
src/util.h
src/wallet/wallet.cpp

Creates a new file in the consensus directory called consensus.h.
Refactors the file system to stay aligned with BTC and Dash 0.12 updates.
Mining, PoS, and transactions successful. Builds with no new errors or warnings.
- Does the knowledge base need an update? No.
- Does this PR add or change dependencies? No.
- Does this change the chain or fork the network? No.

[Refactor] Adds file consensus.h

---

src/anon/sandstorm/sandstorm.cpp
src/chain.cpp
src/chainparams.cpp
src/chainparams.h
src/kernel.cpp
src/main.cpp
src/main.h
src/qt/darksilkgui.cpp
src/rpc/rpcmining.cpp
src/wallet/wallet.cpp

Shift Static Const Variables to ChainParams member variables.
On Ubuntu 15.04 (Proof: http://pastebin.com/2xEZPCeZ)
N/A
N/A

[Refactor] Shift Static Const Variables to ChainParams

---

src/miner.cpp

removes the debug.log spam from hashmeter
yes, with windows.
old code makes debug.log to gigabytes
- Does the readme or documentaion need an update?
no
- Does this add new C++ dependencies which need to be added?
no
- Does this change the chain or fork the network?
no

[Miner] wallets hashmeter fix by Hexxcointakeover

---

darksilk-qt.pro
src/init.cpp
src/makefile.bsd
src/makefile.linux-mingw
src/makefile.mingw
src/makefile.osx
src/makefile.unix
src/ui_interface.cpp
src/ui_interface.h
src/wallet/db.cpp
src/wallet/db.h
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/walletdb.cpp
src/wallet/walletdb.h

Brings db.cpp/h in line with Bitcoin 12.
Yes.

DB Overhaul to Bitcoin 12

---

src/ui_interface.h
src/wallet/wallet.cpp

Slight edit to LoadWallet and addition to UI_Interface
Yes.

LoadWallet

---

src/version.h

To start a new chain and exclude clients with old code or chain.

[Proto] Bump protocol version to 60800

---

src/wallet/wallet.h

Protocol Bump

---

src/init.cpp
src/init.h

Removes hang at shutdown and changes shutdown procedure to match that of Bitcoin 12.
Yes.

Change Shutdown Procedure to Match Bitcoin 12

---

src/chainparams.cpp

Fix Boost related errors.
Yes.

Fix boost-related compile error

---

src/net.cpp

Refactor BindListenPort Win32 ifndef.
Builds without warning, note or error. However, no windows environment to test.

Refactor Win32 #ifndef for BindListenPort

---

src/net.cpp
src/netbase.cpp

Refactoring ConnectSocket in netbase.
Yes.

ConnectSocket

---

src/ui_interface.h

Missing BannedListChanged in ui_interface.h

---

src/net.cpp
src/net.h
src/qt/clientmodel.cpp
src/qt/debugconsole.cpp
src/ui_interface.h

Node ban list

---

darksilk-qt.sublime-project

Adds Sublime project.
Can build within Sublime with this project 
Yes using Sublime version 3 on Ubuntu

[IDE] Adds Sublime project file.

---

src/crypto/aes.h

ifdef define endif comment change

---

src/netbase.cpp

Suppress Warning

---

README.md
app.json

Modifications to the ReadMe Highlighting Waffle.IO
N/A
N/A
1. Fixes issue # N/A
N/A
- Does the knowledge base need an update? N
- Does this PR add or change dependencies? N
- Does this change the chain or fork the network? N

Modifications to the ReadMe Highlighting Waffle.IO

---

src/limitedmap.h

Bring LimitedMap into line with Bitcoin 12
Builds, connects, syncs, PoS and PoW mines with no issues (Ubuntu 16.04).

LimitedMap brought inline with Bitcoin 12

---

src/amount.cpp
src/amount.h

Bitcoin 12.1 alignment

---

src/bloom.cpp
src/bloom.h

Update bloom to bitcoin 12.1 standard.

---

src/rpc/rpcstormnode.cpp

Fix warnings and upgrade "status" and "winners" code.

Fix warnings and update "status" and "winners" code.

---

src/mruset.h

Align mruset.h with Dash

---

darksilk-qt.pro
src/mruset.h
src/noui.cpp
src/noui.h
src/ui_interface.h

Align noui.cpp/h with Bitcoin 12.1
Yes.

Noui Alignment

---

src/sync.cpp
src/sync.h

Align sync.cpp/h with Bitcoin 12
Build tested and chain cleared and resynced without issue.

Align sync.cpp/h with Bitcoin 12

---

src/base58.h
src/hash.cpp
src/hash.h
src/key.cpp
src/key.h
src/pubkey.cpp
src/pubkey.h
src/wallet/wallet.cpp

ChainCode/BIP32 Hardened Limit/BIP32_EXTKEY_SIZE addition
Yes.

ChainCode/BIP32 Hardened Limit/BIP32_EXTKEY_SIZE addition

---

src/qt/multisiginputentry.cpp

Suppress Warning (comparison between signed/unsigned int)

Suppress Warning (comparison between signed/unsigned int)
